### ISSUE TITLE
vlan bbappend discards patches

### ISSUE THREAD

**Issue by Fighter19** [toradex/meta-fsl-bsp-release#1]
The current [vlan_1.9.bbappend](https://github.com/toradex/meta-fsl-bsp-release/blob/toradex-sumo-4.14.78-1.0.0_ga-bringup/imx/meta-bsp/recipes-connectivity/vlan/vlan_1.9.bbappend) seemingly discards the patches made by meta-openembedded by overriding SRC_URI, effectively resulting in a build error, as a linux folder exists in my home directory.

**Comment by agners** [comment]
Thanks for your issue report. That seems to come straight from the NXP BSP:
https://source.codeaurora.org/external/imx/meta-fsl-bsp-release/tree/imx/meta-bsp/recipes-connectivity/vlan/vlan_1.9.bbappend?h=sumo-4.14.78-1.0.0_ga

Toradex does not plan to further maintain this bring up BSP based on the NXP BSP. We are working on a integration into our official BSP layers currently, first beta version are now available:
https://developer.toradex.com/knowledge-base/board-support-package/openembedded-(core)

If you would like to have this fixed in the NXP BSP, I suggest report it to NXP.

**Comment by Fighter19** [comment]
Thank you for your answer.
